Acquire::https::cds01::SslCert "/etc/ssl/client01.crt";
Acquire::https::cds01::SslKey  "/etc/ssl/client01.key";
Acquire::https::cds01::CaInfo  "/usr/local/share/ca-certificates/infra-lessons-ca.crt";
Acquire::https::cds01::Verify-Peer "true";
Acquire::https::cds01::Verify-Host "true";
