server {
    listen 443 ssl;
    server_name cds01;

    ssl_certificate     /etc/ssl/cds01.crt;
    ssl_certificate_key /etc/ssl/cds01.key;

    ssl_client_certificate /usr/local/share/ca-certificates/infra-lessons-ca.crt;
    ssl_verify_client on;

    access_log /var/log/nginx/access.log mtls;

    root /var/www/html;
    index index.html;

    location /repo/ {
        autoindex on;
    }
}
